import type { Finding } from "@/lib/insights";
import type { AnalysisResult, ColumnStats, Filter, SchemaColumn } from "@/lib/types";

const OPERATOR_LABELS: Record<string, string> = {
    "==": "=",
    "!=": "≠",
    ">=": "≥",
    "<=": "≤",
    contains: "contains",
    ">": ">",
    "<": "<",
};

export const describeFilter = (filter: Filter, columns: SchemaColumn[]) =>
    `${columns[filter.col_index]?.name ?? `column ${filter.col_index + 1}`} ${OPERATOR_LABELS[filter.operator] ?? filter.operator} ${filter.value}`;

const num = (n: number) => n.toLocaleString("en-US", { maximumFractionDigits: 2 });

function columnSection(column: SchemaColumn, stats: ColumnStats): string {
    const present = stats.total_count - stats.null_count;
    const lines = [`### ${column.name} (${column.col_type})`, ""];
    lines.push(`- Rows: ${num(stats.total_count)}, filled: ${num(present)}, missing: ${num(stats.null_count)}`);

    if ((column.col_type === "Integer" || column.col_type === "Float") && stats.numeric_count === 0) {
        lines.push("- No numeric values in the analyzed rows");
    } else if (column.col_type === "Integer" || column.col_type === "Float") {
        const std = stats.numeric_count > 1 ? Math.sqrt(stats.m2 / (stats.numeric_count - 1)) : 0;
        lines.push(`- Min ${num(stats.min)}, median ${num(stats.median)}, max ${num(stats.max)}`);
        lines.push(`- Mean ${num(stats.mean)}, std deviation ${num(std)}, quartiles ${num(stats.q1)} to ${num(stats.q3)}`);
    } else {
        lines.push(`- Distinct values: ${num(stats.unique_count_approx)}${stats.is_high_cardinality ? "+" : ""}`);
        if (stats.top_categories.length > 0) {
            lines.push("- Most common: " + stats.top_categories.map((c) => `${c.name || "(empty)"} (${num(c.value)})`).join(", "));
        }
    }
    return lines.join("\n");
}

export function buildReport(
    fileName: string,
    columns: SchemaColumn[],
    analysis: AnalysisResult,
    findings: Finding[],
    filters: Filter[]
): string {
    const out = [`# Data profile: ${fileName}`, ""];
    out.push(`- Rows analyzed: ${num(analysis.rows_processed)}`);
    out.push(`- Columns: ${columns.length}`);
    out.push(`- Duplicate rows: ${analysis.duplicates_capped ? "at least " : ""}${num(analysis.duplicate_rows)}`);
    if (filters.length > 0) {
        out.push(`- Filters applied: ${filters.map((f) => describeFilter(f, columns)).join(" AND ")}`);
    }
    out.push("", "Generated by LocalCrunch. The file was processed in the browser and never uploaded.", "");

    out.push("## Findings", "");
    if (findings.length === 0) {
        out.push("No issues found.");
    } else {
        for (const f of findings) {
            const where = f.columnIndex === null ? "Dataset" : columns[f.columnIndex].name;
            out.push(`- **${f.severity === "warning" ? "Warning" : "Note"}, ${where}: ${f.title}.** ${f.detail}`);
        }
    }

    out.push("", "## Columns", "");
    columns.forEach((column, i) => {
        if (analysis.columns[i]) out.push(columnSection(column, analysis.columns[i]), "");
    });

    return out.join("\n");
}
