[package]
name = "cruncher_core"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Streaming CSV profiling engine for LocalCrunch, compiled to WebAssembly."

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
csv = "1.4.0"
serde = { version = "1.0.228", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
chrono = "0.4.43"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
